# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangunan_corong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('CR', 'BANGUNAN CORONG')], default='CR', max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('debit', models.CharField(max_length=20)),
                ('luas_terairi', models.CharField(max_length=20)),
                ('letak', models.CharField(max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
