# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0002_remove_bangunan_corong_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangunan_sadap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('debit', models.CharField(max_length=20)),
                ('luas_terairi', models.CharField(max_length=20)),
                ('letak', models.CharField(max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
