# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0005_remove_bangunan_sadap_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan_sadap',
            name='letak',
            field=models.CharField(default='LETAK', max_length=100),
            preserve_default=False,
        ),
    ]
