# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0007_auto_20180924_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan_sadap',
            name='category',
            field=models.CharField(blank=True, choices=[('SD', 'BANGUNAN SADAP')], default='SD', max_length=100),
        ),
        migrations.AddField(
            model_name='bangunan_sadap',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
