# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0008_auto_20180924_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan_corong',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
