# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0009_bangunan_corong_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunan_corong',
            name='foto',
            field=models.ImageField(blank=True, default='noPic.jpg', upload_to=''),
        ),
    ]
