# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0011_auto_20180925_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunan_corong',
            name='foto',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
