# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0014_auto_20180925_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunan_corong',
            name='category',
            field=models.CharField(blank=True, choices=[('Bangunan Corong', 'BANGUNAN CORONG')], default='Bangunan Corong', max_length=100),
        ),
    ]
