# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0017_auto_20180928_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunan_corong',
            name='debit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bangunan_corong',
            name='luas_terairi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bangunan_sadap',
            name='debit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bangunan_sadap',
            name='luas_terairi',
            field=models.CharField(max_length=20),
        ),
    ]
