# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0019_laporan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='nama',
        ),
    ]
