# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0020_auto_20180930_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laporan',
            new_name='laporanKerusakan',
        ),
    ]
