# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0021_auto_20180930_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='laporanKerusakan',
        ),
    ]
