# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0022_delete_laporankerusakan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanKerusakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
