# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0023_laporankerusakan'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankerusakan',
            name='deskripsiKerusakan',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='laporankerusakan',
            name='noTelepon',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
