# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0024_auto_20181001_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporankerusakan',
            name='deskripsiKerusakan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laporankerusakan',
            name='noTelepon',
            field=models.CharField(max_length=20),
        ),
    ]
