# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0025_auto_20181001_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankerusakan',
            name='lokasiKerusakan',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
