# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0026_laporankerusakan_lokasikerusakan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporankerusakan',
            name='lokasiKerusakan',
            field=models.CharField(max_length=50),
        ),
    ]
