# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-30 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0027_auto_20181001_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangunan_bendung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Bangunan Bendung', 'BANGUNAN BENDUNG')], default='Bangunan Bendung', max_length=100)),
                ('letak', models.CharField(max_length=50)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, default='noPic.png', upload_to='')),
            ],
        ),
    ]
