# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0028_bangunan_bendung'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan_sadap',
            name='foto',
            field=models.ImageField(blank=True, default='noPic.png', upload_to=''),
        ),
    ]
