# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0029_bangunan_sadap_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangunan_sadap',
            name='category',
            field=models.CharField(blank=True, choices=[('Bangunan Sadap', 'BANGUNAN SADAP')], default='Bangunan Sadap', max_length=100),
        ),
    ]
