# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0030_auto_20181001_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankerusakan',
            name='foto',
            field=models.ImageField(blank=True, default='noPic.png', upload_to=''),
        ),
    ]
