# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0031_laporankerusakan_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangunan_bendung',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bangunan_bendung',
            name='longitude',
        ),
    ]
