# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0037_auto_20181022_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankerusakan',
            name='foto2',
            field=models.ImageField(blank=True, default='noPic.png', upload_to=''),
        ),
    ]
