# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-03 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar_irigasi', '0038_laporankerusakan_foto2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan_bendung',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bangunan_bendung',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bangunan_corong',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bangunan_corong',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bangunan_sadap',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bangunan_sadap',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='laporankerusakan',
            name='foto',
            field=models.ImageField(default='noPic.png', upload_to=''),
        ),
    ]
